### ISSUE TITLE
Printing Not Working

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#313]
Attempt to print displays printer dialog, but selecting print button only closes dialog - nothing shows up in printer queue. As a test, to make sure printer was functioning properly, I exported the recipe to PDF and printed that PDF using other software, which worked fine.

Open a recipe card in RC1. Select Print from menu. Select printer and  click print button.

### Expected Behavior
Selecting print from menu, selecting the printer and clicking print should put item in printer queue.

### Current Behavior
Attempting to print only closes the printer dialogue without placing the item in the printer queue - nothing gets printed.

### Environment
gourmet-c3ece056
Operating System: Ubuntu 20.04 (with latest updates)
Desktop: Cinnamon 4.4.8
Installed as Flatpak

**Comment by cydanil** [comment]
Ok, this is a work in progress.  
The issue is two-fold: on one hand, there was a bug retrieving the print settings, thus failing silently.  
This is now resolved.

On the other hand, there's a problem encoding text in all PDF exports, resulting in the following:
![IMG_20201113_185456](https://user-images.githubusercontent.com/2159577/99104864-dc5ec600-25e1-11eb-8e2c-a3d8763b23b0.jpg)

This is due to an issue at the border between the flatpak and the system, where a temporary PDF is created but fails to load fonts somehow. It's still a bit unclear to me at the moment.

**Comment by zombiewoof** [comment]
Not a problem, for me. I was only letting you know that a problem still exists.

Maybe a tmp file could be created, printed, then deleted? I know it's a bit around-about, but might work.

With PDF export working, I'm in pretty good shape :-)
